// Generated by generate-bindings.py from SwedishTaxFFI.h. Do not edit.
using System.Runtime.InteropServices;

namespace SwedishTax.Native;

internal static unsafe class NativeTax
{
    internal const uint SWEDISH_TAX_STATUS_OK = 0;
    internal const uint SWEDISH_TAX_STATUS_INVALID_INPUT = 1;
    internal const uint SWEDISH_TAX_STATUS_INTERNAL_ERROR = 2;
    internal const uint SWEDISH_TAX_DEDUCTION_AMOUNT = 0;
    internal const uint SWEDISH_TAX_DEDUCTION_PERCENT = 1;

    [StructLayout(LayoutKind.Sequential)]
    internal struct SwedishTaxDeductionResult
    {
        public uint status;
        public uint kind;
        public uint value;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct SwedishTaxAnnualTaxResult
    {
        public uint status;
        public uint assessed_income;
        public uint basic_allowance;
        public uint taxable_income;
        public uint state_income_tax;
        public uint municipal_income_tax;
        public uint burial_and_religious_fee;
        public uint pension_fee;
        public uint pension_fee_credit;
        public uint work_income_credit;
        public uint sickness_compensation_credit;
        public uint earned_income_credit;
        public uint public_service_fee;
        public uint total;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct SwedishTaxAdjustmentCalibration
    {
        public uint basis_income;
        public uint percent;
        public uint formula_tax_at_basis;
        public uint assumed_tax_at_basis;
        public long implied_tax_adjustment;
        public uint projected_ordinary_tax;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct SwedishTaxWithholdingEntry
    {
        public ulong entry_id;
        public uint gross;
        public uint withheld;
        public uint regular_withheld;
        public uint supplemental_withheld;
        public uint additional_withheld;
        public uint rule_kind;
        public uint rule_column;
        public uint rule_percent;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct SwedishTaxIncomeBasis
    {
        public uint kind;
        public uint estimated_basis;
        public uint maximum_basis;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct SwedishTaxCalculationResult
    {
        public uint status;
        public uint monthly_income;
        public uint annual_income;
        public uint ordinary_income;
        public uint work_income;
        public uint pension_income;
        public uint dividend_income;
        public uint sgi_annual_rate;
        public uint deduction_kind;
        public uint deduction_value;
        public SwedishTaxAnnualTaxResult annual_tax;
        public uint has_adjustment_calibration;
        public SwedishTaxAdjustmentCalibration adjustment_calibration;
        public uint ordinary_final_tax;
        public uint dividend_tax;
        public uint total_tax;
        public uint withholding_total;
        public SwedishTaxWithholdingEntry* withholding_entries;
        public nuint withholding_entries_count;
        public nuint withholding_entries_capacity;
        public uint withheld_tax;
        public uint regular_pension_premiums;
        public uint vacation_pension_premiums;
        public uint salary_exchange_sacrifice;
        public uint salary_exchange_pension_contributions;
        public uint pension_salary_basis;
        public uint employer_pension_contributions;
        public double marginal_rate;
        public SwedishTaxIncomeBasis pension_progress;
        public SwedishTaxIncomeBasis sgi_progress;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct SwedishTaxDate
    {
        public uint month;
        public uint day;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct SwedishTaxOptionalU32
    {
        public uint is_some;
        public uint value;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct SwedishTaxVacationCompensation
    {
        public uint is_some;
        public uint annual_entitlement_days;
        public uint payout_days;
        public uint rate_basis_points;
        public uint included_in_pension_salary_basis;
        public SwedishTaxOptionalU32 pension_premium_override;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct SwedishTaxRegularPensionPremium
    {
        public uint is_some;
        public SwedishTaxOptionalU32 monthly_override;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct SwedishTaxSalaryExchange
    {
        public uint is_some;
        public uint sacrificed_salary;
        public uint employer_adds_uplift;
        public uint uplift_basis_points;
        public SwedishTaxOptionalU32 previous_year_pension_salary_basis;
        public SwedishTaxOptionalU32 pension_and_insurance_costs_before_exchange;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct SwedishTaxIncomeEntry
    {
        public ulong id;
        public uint kind;
        public uint amount;
        public SwedishTaxDate start;
        public SwedishTaxDate end;
        public uint use_annual_daily_rate_for_partial_months;
        public uint payer_role;
        public uint own_company_sourced;
        public uint adjustment_applies;
        public uint use_full_year_projection_as_adjustment_basis;
        public SwedishTaxOptionalU32 additional_withholding_per_payment;
        public SwedishTaxOptionalU32 actual_withholding;
        public SwedishTaxVacationCompensation vacation_compensation;
        public SwedishTaxRegularPensionPremium regular_pension_premium;
        public SwedishTaxSalaryExchange salary_exchange;
        public uint included_in_pension_salary_basis;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct SwedishTaxDividendAllowanceInputs
    {
        public uint one_person_company;
        public uint ownership_basis_points;
        public uint other_qualified_ownership_basis_points;
        public uint spouse_ownership_basis_points;
        public uint company_cash_payroll_2026;
        public uint highest_related_cash_salary_2026;
        public uint acquisition_cost;
        public SwedishTaxOptionalU32 acquisition_cost_interest_basis_points;
        public uint saved_allowance;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct SwedishTaxPlanRequest
    {
        public uint table;
        public uint age_group;
        public SwedishTaxIncomeEntry* entries;
        public nuint entries_count;
        public SwedishTaxOptionalU32 adjustment_percent;
        public SwedishTaxDividendAllowanceInputs dividend_allowance;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct SwedishTaxDividendAllowanceResult
    {
        public uint status;
        public uint issue_kind;
        public uint basic_amount;
        public uint owner_cash_salary;
        public uint company_cash_payroll;
        public uint joint_wage_basis;
        public uint joint_wage_basis_after_deduction;
        public uint wage_allowance_before_cap;
        public uint wage_cap_salary;
        public uint wage_cap;
        public uint wage_allowance;
        public uint acquisition_cost_interest_basis;
        public uint acquisition_cost_interest;
        public uint saved_allowance;
        public uint total;
        public uint tax_at_twenty_percent;
        public uint net_after_twenty_percent_tax;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct SwedishTaxPlanTotals
    {
        public uint work_income;
        public uint pension_income;
        public uint dividend_income;
        public uint sgi_annual_rate;
        public uint adjustment_basis_work_income;
        public uint pension_salary_basis;
        public uint regular_pension_premiums;
        public uint vacation_pension_premiums;
        public uint salary_exchange_sacrifice;
        public uint salary_exchange_pension_contributions;
        public uint ordinary_income;
        public uint monthly_taxable_income;
        public uint gross_income;
        public uint total_employer_pension_contributions;
        public double employer_pension_share_of_basis;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct SwedishTaxMonthlyAmounts
    {
        public uint january;
        public uint february;
        public uint march;
        public uint april;
        public uint may;
        public uint june;
        public uint july;
        public uint august;
        public uint september;
        public uint october;
        public uint november;
        public uint december;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct SwedishTaxExchangeAllowance
    {
        public uint ceiling;
        public uint pension_salary_basis_before;
        public uint pension_salary_basis_after;
        public SwedishTaxOptionalU32 previous_year_pension_salary_basis;
        public SwedishTaxOptionalU32 pension_and_insurance_costs_before_exchange;
        public uint pension_contributions_before;
        public uint regular_pension_premiums;
        public uint vacation_pension_premiums;
        public uint other_exchange_contributions;
        public uint selected_exchange_contribution;
        public uint total_employer_pension_contributions;
        public uint available_contribution;
        public uint maximum_sacrifice;
        public double contribution_share_of_basis;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct SwedishTaxEntrySupport
    {
        public uint status;
        public ulong entry_id;
        public uint annual_amount;
        public uint total_annual_amount;
        public uint withholding_payment_count;
        public uint requested_additional_withholding;
        public uint vacation_compensation_amount;
        public uint regular_pension_premium_amount;
        public uint vacation_pension_premium_amount;
        public uint salary_exchange_sacrifice;
        public uint salary_exchange_pension_contribution;
        public uint pension_salary_basis_amount;
        public uint full_year_adjustment_basis_amount;
        public uint is_valid;
        public uint pension_benchmark_monthly;
        public uint suggested_vacation_days;
        public double vacation_amount_per_day;
        public SwedishTaxMonthlyAmounts monthly_amounts;
        public uint has_allowance;
        public SwedishTaxExchangeAllowance allowance;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct SwedishTaxPlanSupport
    {
        public uint status;
        public uint issue_kind;
        public ulong issue_entry_id;
        public uint issue_maximum;
        public SwedishTaxPlanTotals totals;
        public uint has_uniform_monthly_table_reference;
        public uint salary_column;
        public uint pension_column;
        public SwedishTaxEntrySupport* entries;
        public nuint entries_count;
        public nuint entries_capacity;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct SwedishTaxPlanningPolicy
    {
        public uint regular_pension_monthly_threshold;
        public uint default_vacation_rate_basis_points;
        public uint default_exchange_uplift_basis_points;
        public uint employer_pension_allowance_maximum;
        public uint acquisition_cost_threshold;
    }

    [DllImport("libswedish_tax_ios", EntryPoint = "swedish_tax_monthly_deduction", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern SwedishTaxDeductionResult MonthlyDeduction(uint table, uint column, uint gross_monthly_income);

    [DllImport("libswedish_tax_ios", EntryPoint = "swedish_tax_annual_tax", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern SwedishTaxAnnualTaxResult AnnualTax(uint table, uint column, uint gross_yearly_income);

    [DllImport("libswedish_tax_ios", EntryPoint = "swedish_tax_annual_tax_for_income_profile", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern SwedishTaxAnnualTaxResult AnnualTaxForIncomeProfile(uint table, uint age_group, uint work_income, uint pension_income);

    [DllImport("libswedish_tax_ios", EntryPoint = "swedish_tax_calculate_plan", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern SwedishTaxCalculationResult CalculatePlan(SwedishTaxPlanRequest* request);

    [DllImport("libswedish_tax_ios", EntryPoint = "swedish_tax_dividend_allowance_for_plan", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern SwedishTaxDividendAllowanceResult DividendAllowanceForPlan(SwedishTaxPlanRequest* request);

    [DllImport("libswedish_tax_ios", EntryPoint = "swedish_tax_calculation_result_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void CalculationResultFree(SwedishTaxCalculationResult result);

    [DllImport("libswedish_tax_ios", EntryPoint = "swedish_tax_plan_support", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern SwedishTaxPlanSupport PlanSupport(SwedishTaxPlanRequest* request);

    [DllImport("libswedish_tax_ios", EntryPoint = "swedish_tax_plan_support_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void PlanSupportFree(SwedishTaxPlanSupport result);

    [DllImport("libswedish_tax_ios", EntryPoint = "swedish_tax_entry_support", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern SwedishTaxEntrySupport EntrySupport(SwedishTaxIncomeEntry* entry);

    [DllImport("libswedish_tax_ios", EntryPoint = "swedish_tax_planning_policy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern SwedishTaxPlanningPolicy PlanningPolicy();
}
