#!/usr/bin/env python3
"""Generate P/Invoke declarations and ABI checks for the current C header subset.

Reject unsupported declarations rather than guessing their marshalling rules.
"""
import argparse
from pathlib import Path
import re

HERE = Path(__file__).resolve().parent
SCALARS = {"uint32_t": "uint", "uint64_t": "ulong", "int64_t": "long", "size_t": "nuint", "double": "double", "void": "void"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--header", type=Path, default=HERE.parents[2] / "swedish-tax/ios-ffi/include/SwedishTaxFFI.h")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    header = args.header.read_text()
    clean = re.sub(r"/\*.*?\*/|//[^\n]*", "", header, flags=re.S)
    structs = {}
    for name, body in re.findall(r"typedef struct (\w+)\s*\{([^}]+)\}\s*\w+;", clean):
        fields = []
        for declaration in body.split(";"):
            if not declaration.strip():
                continue
            match = re.fullmatch(r"\s*((?:const\s+)?(?:struct\s+)?\w+\s*\*?)\s*(\w+)\s*", declaration)
            if not match:
                raise SystemExit(f"Unsupported C field: {declaration}")
            fields.append((re.sub(r"\s+", " ", match[1].strip()), match[2]))
        structs[name] = fields

    def cs_type(ctype):
        base = ctype.removeprefix("const ").removeprefix("struct ").strip()
        if base.endswith("*"):
            return cs_type(base[:-1].strip()) + "*"
        if base in structs:
            return base
        if base not in SCALARS:
            raise SystemExit(f"Unsupported C type: {ctype}")
        return SCALARS[base]

    functions = re.findall(r"(?:struct\s+)?(\w+)\s+(swedish_tax_\w+)\s*\(([^)]*)\)\s*;", clean)
    if len(functions) != len(re.findall(r"\bswedish_tax_\w+\s*\(", clean)):
        raise SystemExit("Unsupported C function declaration")
    cs = ["// Generated by generate-bindings.py from SwedishTaxFFI.h. Do not edit.",
          "using System.Runtime.InteropServices;", "", "namespace RustPInvoke;", "",
          "internal static unsafe class NativeTax", "{"]
    for name, value in re.findall(r"#define (SWEDISH_TAX_\w+) (\d+)", clean):
        cs.append(f"    internal const uint {name} = {value};")
    for name, fields in structs.items():
        cs += ["", "    [StructLayout(LayoutKind.Sequential)]", f"    internal struct {name}", "    {"]
        cs += [f"        public {cs_type(ctype)} {field};" for ctype, field in fields]
        cs.append("    }")
    for result, entrypoint, parameters in functions:
        args_cs = []
        if parameters.strip() != "void":
            for parameter in parameters.split(","):
                match = re.fullmatch(r"\s*((?:const\s+)?(?:struct\s+)?\w+\s*\*?)\s*(\w+)\s*", parameter)
                if not match:
                    raise SystemExit(f"Unsupported parameter: {parameter}")
                args_cs.append(f"{cs_type(re.sub(r'\s+', ' ', match[1].strip()))} {match[2]}")
        method = "".join(part.title() for part in entrypoint.removeprefix("swedish_tax_").split("_"))
        cs += ["", f'    [DllImport("libswedish_tax_ios", EntryPoint = "{entrypoint}", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]',
               f"    internal static extern {cs_type(result)} {method}({', '.join(args_cs)});"]
    cs.append("}")

    probe = ['// Generated by generate-bindings.py. Test instrumentation only.',
             '#include "obj/SwedishTaxFFI.h"', '', 'uint32_t swedish_tax_probe_layout(uint32_t index) {', '    switch (index) {']
    layout = ["// Generated by generate-bindings.py. Do not edit.", "using System.Runtime.InteropServices;", "", "namespace RustPInvoke;", "",
              "internal static class LayoutChecks", "{",
              '    [DllImport("abi_probe", EntryPoint = "swedish_tax_probe_layout", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]',
              "    private static extern uint NativeLayout(uint index);", "", "    internal static int Verify()", "    {"]
    index = 0
    for name, fields in structs.items():
        pairs = [(f"sizeof({name})", f"Marshal.SizeOf<NativeTax.{name}>()", name)]
        pairs += [(f"offsetof({name}, {field})", f'(int)Marshal.OffsetOf<NativeTax.{name}>("{field}")', f"{name}.{field}") for _, field in fields]
        for native, managed, label in pairs:
            probe.append(f"    case {index}: return (uint32_t){native};")
            layout.append(f'        Check({index}, {managed}, "{label}");')
            index += 1
    probe += ["    default: return UINT32_MAX;", "    }", "}"]
    layout += [f"        return {index};", "    }", "", "    private static void Check(uint index, int managed, string field)", "    {",
               "        var native = NativeLayout(index);", '        if (managed != native) throw new InvalidOperationException($"C ABI layout mismatch for {field}: C# {managed}, C {native}");', "    }", "}"]

    # Field-by-field native fixtures and managed comparisons avoid depending on
    # padding bytes or serializing raw pointers. Only result structures are used.
    serializers = ['// Generated by generate-bindings.py. Native reference fixtures.', '#include <inttypes.h>', '#include <stdio.h>']
    assertions = ['// Generated by generate-bindings.py. Do not edit.', 'using System.Text.Json;', '', 'namespace RustPInvoke;', '', 'internal static unsafe class NativeAssertions', '{']
    readers = ['// Generated by generate-bindings.py. Test fixture input decoding only.', 'using System.Text.Json;', '', 'namespace RustPInvoke;', '', 'internal static unsafe class NativeFixtureInputs', '{']
    for name in structs:
        serializers += [f"static inline void print_{name}({name} value) {{", '    putchar(\'{\');']
        assertions += [f"    internal static void Check(NativeTax.{name} value, JsonElement expected)", "    {"]
        readers += [f"    internal static NativeTax.{name} Read{name}(JsonElement value) => new()", "    {"]
        first = True
        for ctype, field in structs[name]:
            mapped = cs_type(ctype)
            if field.endswith("_capacity"):
                continue  # Allocation capacity is not a cross-platform value.
            serializers.append(f'    printf("{("" if first else ",")}\\\"{field}\\\":");')
            first = False
            if mapped.endswith("*"):
                if field not in ("withholding_entries", "entries"):
                    raise SystemExit(f"Unsupported result pointer: {field}")
                base = mapped[:-1]
                serializers += ["    putchar('[');", f"    for (size_t i = 0; i < value.{field}_count; i++) {{", "        if (i) putchar(',');", f"        print_{base}(value.{field}[i]);", "    }", "    putchar(']');"]
                bounds = f"value.{field}_count > value.{field}_capacity || " if any(f == field + "_capacity" for _, f in structs[name]) else ""
                assertions += [f"        if ({bounds}(value.{field}_count != 0 && value.{field} == null)) throw new InvalidOperationException(\"Invalid Rust result buffer\");",
                               f'        var rows = expected.GetProperty("{field}");', f"        if ((nuint)rows.GetArrayLength() != value.{field}_count) throw new InvalidOperationException(\"Withholding count mismatch\");",
                               f"        for (int i = 0; i < rows.GetArrayLength(); i++) Check(value.{field}[i], rows[i]);"]
            elif mapped in structs:
                serializers.append(f"    print_{mapped}(value.{field});")
                assertions.append(f'        Check(value.{field}, expected.GetProperty("{field}"));')
                readers.append(f'        {field} = Read{mapped}(value.GetProperty("{field}")),')
            else:
                formats = {"uint": '"%" PRIu32', "ulong": '"%" PRIu64', "long": '"%" PRId64', "nuint": '"%zu"', "double": '"%.17g"'}
                serializers.append(f"    printf({formats[mapped]}, value.{field});")
                get = {"uint": "GetUInt32", "ulong": "GetUInt64", "long": "GetInt64", "nuint": "GetUInt64", "double": "GetDouble"}[mapped]
                readers.append(f'        {field} = checked(({mapped})value.GetProperty("{field}").{get}()),')
                other = f'expected.GetProperty("{field}").{get}()'
                test = f"!double.IsFinite(value.{field}) || Math.Abs(value.{field} - {other}) > 1e-10" if mapped == "double" else f"value.{field} != {other}"
                assertions.append(f'        if ({test}) throw new InvalidOperationException("Value mismatch: {name}.{field}");')
        serializers += ["    putchar('}');", "}"]
        assertions.append("    }")
        readers.append("    };")
    assertions.append("}")
    readers.append("}")
    outputs = {"NativeTax.g.cs": cs, "abi_probe.c": probe, "LayoutChecks.g.cs": layout,
               "reference_serializers.h": serializers, "NativeAssertions.g.cs": assertions, "NativeFixtureInputs.g.cs": readers}
    for filename, lines in outputs.items():
        destination = HERE / filename
        content = "\n".join(lines) + "\n"
        if args.check:
            if not destination.exists() or destination.read_text() != content:
                raise SystemExit(f"Generated binding drift: {filename}; run generate-bindings.py")
        else:
            destination.write_text(content)
    production = HERE.parents[1] / "src/SwedishTax.Native/NativeTax.g.cs"
    content = "\n".join(cs).replace("namespace RustPInvoke;", "namespace SwedishTax.Native;") + "\n"
    if args.check:
        if not production.exists() or production.read_text() != content:
            raise SystemExit("Generated production P/Invoke declarations differ from the C header")
    else:
        production.parent.mkdir(parents=True, exist_ok=True)
        production.write_text(content)
    print(f"{'Checked' if args.check else 'Generated'} {len(functions)} functions, {len(structs)} structs, {index} ABI layout checks")


if __name__ == "__main__":
    main()
