// Generated by generate-bindings.py. Test fixture input decoding only.
using System.Text.Json;

namespace RustPInvoke;

internal static unsafe class NativeFixtureInputs
{
    internal static NativeTax.SwedishTaxDeductionResult ReadSwedishTaxDeductionResult(JsonElement value) => new()
    {
        status = checked((uint)value.GetProperty("status").GetUInt32()),
        kind = checked((uint)value.GetProperty("kind").GetUInt32()),
        value = checked((uint)value.GetProperty("value").GetUInt32()),
    };
    internal static NativeTax.SwedishTaxAnnualTaxResult ReadSwedishTaxAnnualTaxResult(JsonElement value) => new()
    {
        status = checked((uint)value.GetProperty("status").GetUInt32()),
        assessed_income = checked((uint)value.GetProperty("assessed_income").GetUInt32()),
        basic_allowance = checked((uint)value.GetProperty("basic_allowance").GetUInt32()),
        taxable_income = checked((uint)value.GetProperty("taxable_income").GetUInt32()),
        state_income_tax = checked((uint)value.GetProperty("state_income_tax").GetUInt32()),
        municipal_income_tax = checked((uint)value.GetProperty("municipal_income_tax").GetUInt32()),
        burial_and_religious_fee = checked((uint)value.GetProperty("burial_and_religious_fee").GetUInt32()),
        pension_fee = checked((uint)value.GetProperty("pension_fee").GetUInt32()),
        pension_fee_credit = checked((uint)value.GetProperty("pension_fee_credit").GetUInt32()),
        work_income_credit = checked((uint)value.GetProperty("work_income_credit").GetUInt32()),
        sickness_compensation_credit = checked((uint)value.GetProperty("sickness_compensation_credit").GetUInt32()),
        earned_income_credit = checked((uint)value.GetProperty("earned_income_credit").GetUInt32()),
        public_service_fee = checked((uint)value.GetProperty("public_service_fee").GetUInt32()),
        total = checked((uint)value.GetProperty("total").GetUInt32()),
    };
    internal static NativeTax.SwedishTaxAdjustmentCalibration ReadSwedishTaxAdjustmentCalibration(JsonElement value) => new()
    {
        basis_income = checked((uint)value.GetProperty("basis_income").GetUInt32()),
        percent = checked((uint)value.GetProperty("percent").GetUInt32()),
        formula_tax_at_basis = checked((uint)value.GetProperty("formula_tax_at_basis").GetUInt32()),
        assumed_tax_at_basis = checked((uint)value.GetProperty("assumed_tax_at_basis").GetUInt32()),
        implied_tax_adjustment = checked((long)value.GetProperty("implied_tax_adjustment").GetInt64()),
        projected_ordinary_tax = checked((uint)value.GetProperty("projected_ordinary_tax").GetUInt32()),
    };
    internal static NativeTax.SwedishTaxWithholdingEntry ReadSwedishTaxWithholdingEntry(JsonElement value) => new()
    {
        entry_id = checked((ulong)value.GetProperty("entry_id").GetUInt64()),
        gross = checked((uint)value.GetProperty("gross").GetUInt32()),
        withheld = checked((uint)value.GetProperty("withheld").GetUInt32()),
        regular_withheld = checked((uint)value.GetProperty("regular_withheld").GetUInt32()),
        supplemental_withheld = checked((uint)value.GetProperty("supplemental_withheld").GetUInt32()),
        additional_withheld = checked((uint)value.GetProperty("additional_withheld").GetUInt32()),
        rule_kind = checked((uint)value.GetProperty("rule_kind").GetUInt32()),
        rule_column = checked((uint)value.GetProperty("rule_column").GetUInt32()),
        rule_percent = checked((uint)value.GetProperty("rule_percent").GetUInt32()),
    };
    internal static NativeTax.SwedishTaxIncomeBasis ReadSwedishTaxIncomeBasis(JsonElement value) => new()
    {
        kind = checked((uint)value.GetProperty("kind").GetUInt32()),
        estimated_basis = checked((uint)value.GetProperty("estimated_basis").GetUInt32()),
        maximum_basis = checked((uint)value.GetProperty("maximum_basis").GetUInt32()),
    };
    internal static NativeTax.SwedishTaxCalculationResult ReadSwedishTaxCalculationResult(JsonElement value) => new()
    {
        status = checked((uint)value.GetProperty("status").GetUInt32()),
        monthly_income = checked((uint)value.GetProperty("monthly_income").GetUInt32()),
        annual_income = checked((uint)value.GetProperty("annual_income").GetUInt32()),
        ordinary_income = checked((uint)value.GetProperty("ordinary_income").GetUInt32()),
        work_income = checked((uint)value.GetProperty("work_income").GetUInt32()),
        pension_income = checked((uint)value.GetProperty("pension_income").GetUInt32()),
        dividend_income = checked((uint)value.GetProperty("dividend_income").GetUInt32()),
        sgi_annual_rate = checked((uint)value.GetProperty("sgi_annual_rate").GetUInt32()),
        deduction_kind = checked((uint)value.GetProperty("deduction_kind").GetUInt32()),
        deduction_value = checked((uint)value.GetProperty("deduction_value").GetUInt32()),
        annual_tax = ReadSwedishTaxAnnualTaxResult(value.GetProperty("annual_tax")),
        has_adjustment_calibration = checked((uint)value.GetProperty("has_adjustment_calibration").GetUInt32()),
        adjustment_calibration = ReadSwedishTaxAdjustmentCalibration(value.GetProperty("adjustment_calibration")),
        ordinary_final_tax = checked((uint)value.GetProperty("ordinary_final_tax").GetUInt32()),
        dividend_tax = checked((uint)value.GetProperty("dividend_tax").GetUInt32()),
        total_tax = checked((uint)value.GetProperty("total_tax").GetUInt32()),
        withholding_total = checked((uint)value.GetProperty("withholding_total").GetUInt32()),
        withholding_entries_count = checked((nuint)value.GetProperty("withholding_entries_count").GetUInt64()),
        withheld_tax = checked((uint)value.GetProperty("withheld_tax").GetUInt32()),
        regular_pension_premiums = checked((uint)value.GetProperty("regular_pension_premiums").GetUInt32()),
        vacation_pension_premiums = checked((uint)value.GetProperty("vacation_pension_premiums").GetUInt32()),
        salary_exchange_sacrifice = checked((uint)value.GetProperty("salary_exchange_sacrifice").GetUInt32()),
        salary_exchange_pension_contributions = checked((uint)value.GetProperty("salary_exchange_pension_contributions").GetUInt32()),
        pension_salary_basis = checked((uint)value.GetProperty("pension_salary_basis").GetUInt32()),
        employer_pension_contributions = checked((uint)value.GetProperty("employer_pension_contributions").GetUInt32()),
        marginal_rate = checked((double)value.GetProperty("marginal_rate").GetDouble()),
        pension_progress = ReadSwedishTaxIncomeBasis(value.GetProperty("pension_progress")),
        sgi_progress = ReadSwedishTaxIncomeBasis(value.GetProperty("sgi_progress")),
    };
    internal static NativeTax.SwedishTaxDate ReadSwedishTaxDate(JsonElement value) => new()
    {
        month = checked((uint)value.GetProperty("month").GetUInt32()),
        day = checked((uint)value.GetProperty("day").GetUInt32()),
    };
    internal static NativeTax.SwedishTaxOptionalU32 ReadSwedishTaxOptionalU32(JsonElement value) => new()
    {
        is_some = checked((uint)value.GetProperty("is_some").GetUInt32()),
        value = checked((uint)value.GetProperty("value").GetUInt32()),
    };
    internal static NativeTax.SwedishTaxVacationCompensation ReadSwedishTaxVacationCompensation(JsonElement value) => new()
    {
        is_some = checked((uint)value.GetProperty("is_some").GetUInt32()),
        annual_entitlement_days = checked((uint)value.GetProperty("annual_entitlement_days").GetUInt32()),
        payout_days = checked((uint)value.GetProperty("payout_days").GetUInt32()),
        rate_basis_points = checked((uint)value.GetProperty("rate_basis_points").GetUInt32()),
        included_in_pension_salary_basis = checked((uint)value.GetProperty("included_in_pension_salary_basis").GetUInt32()),
        pension_premium_override = ReadSwedishTaxOptionalU32(value.GetProperty("pension_premium_override")),
    };
    internal static NativeTax.SwedishTaxRegularPensionPremium ReadSwedishTaxRegularPensionPremium(JsonElement value) => new()
    {
        is_some = checked((uint)value.GetProperty("is_some").GetUInt32()),
        monthly_override = ReadSwedishTaxOptionalU32(value.GetProperty("monthly_override")),
    };
    internal static NativeTax.SwedishTaxSalaryExchange ReadSwedishTaxSalaryExchange(JsonElement value) => new()
    {
        is_some = checked((uint)value.GetProperty("is_some").GetUInt32()),
        sacrificed_salary = checked((uint)value.GetProperty("sacrificed_salary").GetUInt32()),
        employer_adds_uplift = checked((uint)value.GetProperty("employer_adds_uplift").GetUInt32()),
        uplift_basis_points = checked((uint)value.GetProperty("uplift_basis_points").GetUInt32()),
        previous_year_pension_salary_basis = ReadSwedishTaxOptionalU32(value.GetProperty("previous_year_pension_salary_basis")),
        pension_and_insurance_costs_before_exchange = ReadSwedishTaxOptionalU32(value.GetProperty("pension_and_insurance_costs_before_exchange")),
    };
    internal static NativeTax.SwedishTaxIncomeEntry ReadSwedishTaxIncomeEntry(JsonElement value) => new()
    {
        id = checked((ulong)value.GetProperty("id").GetUInt64()),
        kind = checked((uint)value.GetProperty("kind").GetUInt32()),
        amount = checked((uint)value.GetProperty("amount").GetUInt32()),
        start = ReadSwedishTaxDate(value.GetProperty("start")),
        end = ReadSwedishTaxDate(value.GetProperty("end")),
        use_annual_daily_rate_for_partial_months = checked((uint)value.GetProperty("use_annual_daily_rate_for_partial_months").GetUInt32()),
        payer_role = checked((uint)value.GetProperty("payer_role").GetUInt32()),
        own_company_sourced = checked((uint)value.GetProperty("own_company_sourced").GetUInt32()),
        adjustment_applies = checked((uint)value.GetProperty("adjustment_applies").GetUInt32()),
        use_full_year_projection_as_adjustment_basis = checked((uint)value.GetProperty("use_full_year_projection_as_adjustment_basis").GetUInt32()),
        additional_withholding_per_payment = ReadSwedishTaxOptionalU32(value.GetProperty("additional_withholding_per_payment")),
        actual_withholding = ReadSwedishTaxOptionalU32(value.GetProperty("actual_withholding")),
        vacation_compensation = ReadSwedishTaxVacationCompensation(value.GetProperty("vacation_compensation")),
        regular_pension_premium = ReadSwedishTaxRegularPensionPremium(value.GetProperty("regular_pension_premium")),
        salary_exchange = ReadSwedishTaxSalaryExchange(value.GetProperty("salary_exchange")),
        included_in_pension_salary_basis = checked((uint)value.GetProperty("included_in_pension_salary_basis").GetUInt32()),
    };
    internal static NativeTax.SwedishTaxDividendAllowanceInputs ReadSwedishTaxDividendAllowanceInputs(JsonElement value) => new()
    {
        one_person_company = checked((uint)value.GetProperty("one_person_company").GetUInt32()),
        ownership_basis_points = checked((uint)value.GetProperty("ownership_basis_points").GetUInt32()),
        other_qualified_ownership_basis_points = checked((uint)value.GetProperty("other_qualified_ownership_basis_points").GetUInt32()),
        spouse_ownership_basis_points = checked((uint)value.GetProperty("spouse_ownership_basis_points").GetUInt32()),
        company_cash_payroll_2026 = checked((uint)value.GetProperty("company_cash_payroll_2026").GetUInt32()),
        highest_related_cash_salary_2026 = checked((uint)value.GetProperty("highest_related_cash_salary_2026").GetUInt32()),
        acquisition_cost = checked((uint)value.GetProperty("acquisition_cost").GetUInt32()),
        acquisition_cost_interest_basis_points = ReadSwedishTaxOptionalU32(value.GetProperty("acquisition_cost_interest_basis_points")),
        saved_allowance = checked((uint)value.GetProperty("saved_allowance").GetUInt32()),
    };
    internal static NativeTax.SwedishTaxPlanRequest ReadSwedishTaxPlanRequest(JsonElement value) => new()
    {
        table = checked((uint)value.GetProperty("table").GetUInt32()),
        age_group = checked((uint)value.GetProperty("age_group").GetUInt32()),
        entries_count = checked((nuint)value.GetProperty("entries_count").GetUInt64()),
        adjustment_percent = ReadSwedishTaxOptionalU32(value.GetProperty("adjustment_percent")),
        dividend_allowance = ReadSwedishTaxDividendAllowanceInputs(value.GetProperty("dividend_allowance")),
    };
    internal static NativeTax.SwedishTaxDividendAllowanceResult ReadSwedishTaxDividendAllowanceResult(JsonElement value) => new()
    {
        status = checked((uint)value.GetProperty("status").GetUInt32()),
        issue_kind = checked((uint)value.GetProperty("issue_kind").GetUInt32()),
        basic_amount = checked((uint)value.GetProperty("basic_amount").GetUInt32()),
        owner_cash_salary = checked((uint)value.GetProperty("owner_cash_salary").GetUInt32()),
        company_cash_payroll = checked((uint)value.GetProperty("company_cash_payroll").GetUInt32()),
        joint_wage_basis = checked((uint)value.GetProperty("joint_wage_basis").GetUInt32()),
        joint_wage_basis_after_deduction = checked((uint)value.GetProperty("joint_wage_basis_after_deduction").GetUInt32()),
        wage_allowance_before_cap = checked((uint)value.GetProperty("wage_allowance_before_cap").GetUInt32()),
        wage_cap_salary = checked((uint)value.GetProperty("wage_cap_salary").GetUInt32()),
        wage_cap = checked((uint)value.GetProperty("wage_cap").GetUInt32()),
        wage_allowance = checked((uint)value.GetProperty("wage_allowance").GetUInt32()),
        acquisition_cost_interest_basis = checked((uint)value.GetProperty("acquisition_cost_interest_basis").GetUInt32()),
        acquisition_cost_interest = checked((uint)value.GetProperty("acquisition_cost_interest").GetUInt32()),
        saved_allowance = checked((uint)value.GetProperty("saved_allowance").GetUInt32()),
        total = checked((uint)value.GetProperty("total").GetUInt32()),
        tax_at_twenty_percent = checked((uint)value.GetProperty("tax_at_twenty_percent").GetUInt32()),
        net_after_twenty_percent_tax = checked((uint)value.GetProperty("net_after_twenty_percent_tax").GetUInt32()),
    };
    internal static NativeTax.SwedishTaxPlanTotals ReadSwedishTaxPlanTotals(JsonElement value) => new()
    {
        work_income = checked((uint)value.GetProperty("work_income").GetUInt32()),
        pension_income = checked((uint)value.GetProperty("pension_income").GetUInt32()),
        dividend_income = checked((uint)value.GetProperty("dividend_income").GetUInt32()),
        sgi_annual_rate = checked((uint)value.GetProperty("sgi_annual_rate").GetUInt32()),
        adjustment_basis_work_income = checked((uint)value.GetProperty("adjustment_basis_work_income").GetUInt32()),
        pension_salary_basis = checked((uint)value.GetProperty("pension_salary_basis").GetUInt32()),
        regular_pension_premiums = checked((uint)value.GetProperty("regular_pension_premiums").GetUInt32()),
        vacation_pension_premiums = checked((uint)value.GetProperty("vacation_pension_premiums").GetUInt32()),
        salary_exchange_sacrifice = checked((uint)value.GetProperty("salary_exchange_sacrifice").GetUInt32()),
        salary_exchange_pension_contributions = checked((uint)value.GetProperty("salary_exchange_pension_contributions").GetUInt32()),
        ordinary_income = checked((uint)value.GetProperty("ordinary_income").GetUInt32()),
        monthly_taxable_income = checked((uint)value.GetProperty("monthly_taxable_income").GetUInt32()),
        gross_income = checked((uint)value.GetProperty("gross_income").GetUInt32()),
        total_employer_pension_contributions = checked((uint)value.GetProperty("total_employer_pension_contributions").GetUInt32()),
        employer_pension_share_of_basis = checked((double)value.GetProperty("employer_pension_share_of_basis").GetDouble()),
    };
    internal static NativeTax.SwedishTaxMonthlyAmounts ReadSwedishTaxMonthlyAmounts(JsonElement value) => new()
    {
        january = checked((uint)value.GetProperty("january").GetUInt32()),
        february = checked((uint)value.GetProperty("february").GetUInt32()),
        march = checked((uint)value.GetProperty("march").GetUInt32()),
        april = checked((uint)value.GetProperty("april").GetUInt32()),
        may = checked((uint)value.GetProperty("may").GetUInt32()),
        june = checked((uint)value.GetProperty("june").GetUInt32()),
        july = checked((uint)value.GetProperty("july").GetUInt32()),
        august = checked((uint)value.GetProperty("august").GetUInt32()),
        september = checked((uint)value.GetProperty("september").GetUInt32()),
        october = checked((uint)value.GetProperty("october").GetUInt32()),
        november = checked((uint)value.GetProperty("november").GetUInt32()),
        december = checked((uint)value.GetProperty("december").GetUInt32()),
    };
    internal static NativeTax.SwedishTaxExchangeAllowance ReadSwedishTaxExchangeAllowance(JsonElement value) => new()
    {
        ceiling = checked((uint)value.GetProperty("ceiling").GetUInt32()),
        pension_salary_basis_before = checked((uint)value.GetProperty("pension_salary_basis_before").GetUInt32()),
        pension_salary_basis_after = checked((uint)value.GetProperty("pension_salary_basis_after").GetUInt32()),
        previous_year_pension_salary_basis = ReadSwedishTaxOptionalU32(value.GetProperty("previous_year_pension_salary_basis")),
        pension_and_insurance_costs_before_exchange = ReadSwedishTaxOptionalU32(value.GetProperty("pension_and_insurance_costs_before_exchange")),
        pension_contributions_before = checked((uint)value.GetProperty("pension_contributions_before").GetUInt32()),
        regular_pension_premiums = checked((uint)value.GetProperty("regular_pension_premiums").GetUInt32()),
        vacation_pension_premiums = checked((uint)value.GetProperty("vacation_pension_premiums").GetUInt32()),
        other_exchange_contributions = checked((uint)value.GetProperty("other_exchange_contributions").GetUInt32()),
        selected_exchange_contribution = checked((uint)value.GetProperty("selected_exchange_contribution").GetUInt32()),
        total_employer_pension_contributions = checked((uint)value.GetProperty("total_employer_pension_contributions").GetUInt32()),
        available_contribution = checked((uint)value.GetProperty("available_contribution").GetUInt32()),
        maximum_sacrifice = checked((uint)value.GetProperty("maximum_sacrifice").GetUInt32()),
        contribution_share_of_basis = checked((double)value.GetProperty("contribution_share_of_basis").GetDouble()),
    };
    internal static NativeTax.SwedishTaxEntrySupport ReadSwedishTaxEntrySupport(JsonElement value) => new()
    {
        status = checked((uint)value.GetProperty("status").GetUInt32()),
        entry_id = checked((ulong)value.GetProperty("entry_id").GetUInt64()),
        annual_amount = checked((uint)value.GetProperty("annual_amount").GetUInt32()),
        total_annual_amount = checked((uint)value.GetProperty("total_annual_amount").GetUInt32()),
        withholding_payment_count = checked((uint)value.GetProperty("withholding_payment_count").GetUInt32()),
        requested_additional_withholding = checked((uint)value.GetProperty("requested_additional_withholding").GetUInt32()),
        vacation_compensation_amount = checked((uint)value.GetProperty("vacation_compensation_amount").GetUInt32()),
        regular_pension_premium_amount = checked((uint)value.GetProperty("regular_pension_premium_amount").GetUInt32()),
        vacation_pension_premium_amount = checked((uint)value.GetProperty("vacation_pension_premium_amount").GetUInt32()),
        salary_exchange_sacrifice = checked((uint)value.GetProperty("salary_exchange_sacrifice").GetUInt32()),
        salary_exchange_pension_contribution = checked((uint)value.GetProperty("salary_exchange_pension_contribution").GetUInt32()),
        pension_salary_basis_amount = checked((uint)value.GetProperty("pension_salary_basis_amount").GetUInt32()),
        full_year_adjustment_basis_amount = checked((uint)value.GetProperty("full_year_adjustment_basis_amount").GetUInt32()),
        is_valid = checked((uint)value.GetProperty("is_valid").GetUInt32()),
        pension_benchmark_monthly = checked((uint)value.GetProperty("pension_benchmark_monthly").GetUInt32()),
        suggested_vacation_days = checked((uint)value.GetProperty("suggested_vacation_days").GetUInt32()),
        vacation_amount_per_day = checked((double)value.GetProperty("vacation_amount_per_day").GetDouble()),
        monthly_amounts = ReadSwedishTaxMonthlyAmounts(value.GetProperty("monthly_amounts")),
        has_allowance = checked((uint)value.GetProperty("has_allowance").GetUInt32()),
        allowance = ReadSwedishTaxExchangeAllowance(value.GetProperty("allowance")),
    };
    internal static NativeTax.SwedishTaxPlanSupport ReadSwedishTaxPlanSupport(JsonElement value) => new()
    {
        status = checked((uint)value.GetProperty("status").GetUInt32()),
        issue_kind = checked((uint)value.GetProperty("issue_kind").GetUInt32()),
        issue_entry_id = checked((ulong)value.GetProperty("issue_entry_id").GetUInt64()),
        issue_maximum = checked((uint)value.GetProperty("issue_maximum").GetUInt32()),
        totals = ReadSwedishTaxPlanTotals(value.GetProperty("totals")),
        has_uniform_monthly_table_reference = checked((uint)value.GetProperty("has_uniform_monthly_table_reference").GetUInt32()),
        salary_column = checked((uint)value.GetProperty("salary_column").GetUInt32()),
        pension_column = checked((uint)value.GetProperty("pension_column").GetUInt32()),
        entries_count = checked((nuint)value.GetProperty("entries_count").GetUInt64()),
    };
    internal static NativeTax.SwedishTaxPlanningPolicy ReadSwedishTaxPlanningPolicy(JsonElement value) => new()
    {
        regular_pension_monthly_threshold = checked((uint)value.GetProperty("regular_pension_monthly_threshold").GetUInt32()),
        default_vacation_rate_basis_points = checked((uint)value.GetProperty("default_vacation_rate_basis_points").GetUInt32()),
        default_exchange_uplift_basis_points = checked((uint)value.GetProperty("default_exchange_uplift_basis_points").GetUInt32()),
        employer_pension_allowance_maximum = checked((uint)value.GetProperty("employer_pension_allowance_maximum").GetUInt32()),
        acquisition_cost_threshold = checked((uint)value.GetProperty("acquisition_cost_threshold").GetUInt32()),
    };
}
