// Generated by generate-bindings.py. Do not edit.
using System.Text.Json;

namespace RustPInvoke;

internal static unsafe class NativeAssertions
{
    internal static void Check(NativeTax.SwedishTaxDeductionResult value, JsonElement expected)
    {
        if (value.status != expected.GetProperty("status").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDeductionResult.status");
        if (value.kind != expected.GetProperty("kind").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDeductionResult.kind");
        if (value.value != expected.GetProperty("value").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDeductionResult.value");
    }
    internal static void Check(NativeTax.SwedishTaxAnnualTaxResult value, JsonElement expected)
    {
        if (value.status != expected.GetProperty("status").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxAnnualTaxResult.status");
        if (value.assessed_income != expected.GetProperty("assessed_income").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxAnnualTaxResult.assessed_income");
        if (value.basic_allowance != expected.GetProperty("basic_allowance").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxAnnualTaxResult.basic_allowance");
        if (value.taxable_income != expected.GetProperty("taxable_income").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxAnnualTaxResult.taxable_income");
        if (value.state_income_tax != expected.GetProperty("state_income_tax").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxAnnualTaxResult.state_income_tax");
        if (value.municipal_income_tax != expected.GetProperty("municipal_income_tax").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxAnnualTaxResult.municipal_income_tax");
        if (value.burial_and_religious_fee != expected.GetProperty("burial_and_religious_fee").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxAnnualTaxResult.burial_and_religious_fee");
        if (value.pension_fee != expected.GetProperty("pension_fee").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxAnnualTaxResult.pension_fee");
        if (value.pension_fee_credit != expected.GetProperty("pension_fee_credit").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxAnnualTaxResult.pension_fee_credit");
        if (value.work_income_credit != expected.GetProperty("work_income_credit").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxAnnualTaxResult.work_income_credit");
        if (value.sickness_compensation_credit != expected.GetProperty("sickness_compensation_credit").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxAnnualTaxResult.sickness_compensation_credit");
        if (value.earned_income_credit != expected.GetProperty("earned_income_credit").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxAnnualTaxResult.earned_income_credit");
        if (value.public_service_fee != expected.GetProperty("public_service_fee").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxAnnualTaxResult.public_service_fee");
        if (value.total != expected.GetProperty("total").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxAnnualTaxResult.total");
    }
    internal static void Check(NativeTax.SwedishTaxAdjustmentCalibration value, JsonElement expected)
    {
        if (value.basis_income != expected.GetProperty("basis_income").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxAdjustmentCalibration.basis_income");
        if (value.percent != expected.GetProperty("percent").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxAdjustmentCalibration.percent");
        if (value.formula_tax_at_basis != expected.GetProperty("formula_tax_at_basis").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxAdjustmentCalibration.formula_tax_at_basis");
        if (value.assumed_tax_at_basis != expected.GetProperty("assumed_tax_at_basis").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxAdjustmentCalibration.assumed_tax_at_basis");
        if (value.implied_tax_adjustment != expected.GetProperty("implied_tax_adjustment").GetInt64()) throw new InvalidOperationException("Value mismatch: SwedishTaxAdjustmentCalibration.implied_tax_adjustment");
        if (value.projected_ordinary_tax != expected.GetProperty("projected_ordinary_tax").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxAdjustmentCalibration.projected_ordinary_tax");
    }
    internal static void Check(NativeTax.SwedishTaxWithholdingEntry value, JsonElement expected)
    {
        if (value.entry_id != expected.GetProperty("entry_id").GetUInt64()) throw new InvalidOperationException("Value mismatch: SwedishTaxWithholdingEntry.entry_id");
        if (value.gross != expected.GetProperty("gross").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxWithholdingEntry.gross");
        if (value.withheld != expected.GetProperty("withheld").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxWithholdingEntry.withheld");
        if (value.regular_withheld != expected.GetProperty("regular_withheld").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxWithholdingEntry.regular_withheld");
        if (value.supplemental_withheld != expected.GetProperty("supplemental_withheld").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxWithholdingEntry.supplemental_withheld");
        if (value.additional_withheld != expected.GetProperty("additional_withheld").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxWithholdingEntry.additional_withheld");
        if (value.rule_kind != expected.GetProperty("rule_kind").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxWithholdingEntry.rule_kind");
        if (value.rule_column != expected.GetProperty("rule_column").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxWithholdingEntry.rule_column");
        if (value.rule_percent != expected.GetProperty("rule_percent").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxWithholdingEntry.rule_percent");
    }
    internal static void Check(NativeTax.SwedishTaxIncomeBasis value, JsonElement expected)
    {
        if (value.kind != expected.GetProperty("kind").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxIncomeBasis.kind");
        if (value.estimated_basis != expected.GetProperty("estimated_basis").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxIncomeBasis.estimated_basis");
        if (value.maximum_basis != expected.GetProperty("maximum_basis").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxIncomeBasis.maximum_basis");
    }
    internal static void Check(NativeTax.SwedishTaxCalculationResult value, JsonElement expected)
    {
        if (value.status != expected.GetProperty("status").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.status");
        if (value.monthly_income != expected.GetProperty("monthly_income").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.monthly_income");
        if (value.annual_income != expected.GetProperty("annual_income").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.annual_income");
        if (value.ordinary_income != expected.GetProperty("ordinary_income").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.ordinary_income");
        if (value.work_income != expected.GetProperty("work_income").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.work_income");
        if (value.pension_income != expected.GetProperty("pension_income").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.pension_income");
        if (value.dividend_income != expected.GetProperty("dividend_income").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.dividend_income");
        if (value.sgi_annual_rate != expected.GetProperty("sgi_annual_rate").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.sgi_annual_rate");
        if (value.deduction_kind != expected.GetProperty("deduction_kind").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.deduction_kind");
        if (value.deduction_value != expected.GetProperty("deduction_value").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.deduction_value");
        Check(value.annual_tax, expected.GetProperty("annual_tax"));
        if (value.has_adjustment_calibration != expected.GetProperty("has_adjustment_calibration").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.has_adjustment_calibration");
        Check(value.adjustment_calibration, expected.GetProperty("adjustment_calibration"));
        if (value.ordinary_final_tax != expected.GetProperty("ordinary_final_tax").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.ordinary_final_tax");
        if (value.dividend_tax != expected.GetProperty("dividend_tax").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.dividend_tax");
        if (value.total_tax != expected.GetProperty("total_tax").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.total_tax");
        if (value.withholding_total != expected.GetProperty("withholding_total").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.withholding_total");
        if (value.withholding_entries_count > value.withholding_entries_capacity || (value.withholding_entries_count != 0 && value.withholding_entries == null)) throw new InvalidOperationException("Invalid Rust result buffer");
        var rows = expected.GetProperty("withholding_entries");
        if ((nuint)rows.GetArrayLength() != value.withholding_entries_count) throw new InvalidOperationException("Withholding count mismatch");
        for (int i = 0; i < rows.GetArrayLength(); i++) Check(value.withholding_entries[i], rows[i]);
        if (value.withholding_entries_count != expected.GetProperty("withholding_entries_count").GetUInt64()) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.withholding_entries_count");
        if (value.withheld_tax != expected.GetProperty("withheld_tax").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.withheld_tax");
        if (value.regular_pension_premiums != expected.GetProperty("regular_pension_premiums").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.regular_pension_premiums");
        if (value.vacation_pension_premiums != expected.GetProperty("vacation_pension_premiums").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.vacation_pension_premiums");
        if (value.salary_exchange_sacrifice != expected.GetProperty("salary_exchange_sacrifice").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.salary_exchange_sacrifice");
        if (value.salary_exchange_pension_contributions != expected.GetProperty("salary_exchange_pension_contributions").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.salary_exchange_pension_contributions");
        if (value.pension_salary_basis != expected.GetProperty("pension_salary_basis").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.pension_salary_basis");
        if (value.employer_pension_contributions != expected.GetProperty("employer_pension_contributions").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.employer_pension_contributions");
        if (!double.IsFinite(value.marginal_rate) || Math.Abs(value.marginal_rate - expected.GetProperty("marginal_rate").GetDouble()) > 1e-10) throw new InvalidOperationException("Value mismatch: SwedishTaxCalculationResult.marginal_rate");
        Check(value.pension_progress, expected.GetProperty("pension_progress"));
        Check(value.sgi_progress, expected.GetProperty("sgi_progress"));
    }
    internal static void Check(NativeTax.SwedishTaxDate value, JsonElement expected)
    {
        if (value.month != expected.GetProperty("month").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDate.month");
        if (value.day != expected.GetProperty("day").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDate.day");
    }
    internal static void Check(NativeTax.SwedishTaxOptionalU32 value, JsonElement expected)
    {
        if (value.is_some != expected.GetProperty("is_some").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxOptionalU32.is_some");
        if (value.value != expected.GetProperty("value").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxOptionalU32.value");
    }
    internal static void Check(NativeTax.SwedishTaxVacationCompensation value, JsonElement expected)
    {
        if (value.is_some != expected.GetProperty("is_some").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxVacationCompensation.is_some");
        if (value.annual_entitlement_days != expected.GetProperty("annual_entitlement_days").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxVacationCompensation.annual_entitlement_days");
        if (value.payout_days != expected.GetProperty("payout_days").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxVacationCompensation.payout_days");
        if (value.rate_basis_points != expected.GetProperty("rate_basis_points").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxVacationCompensation.rate_basis_points");
        if (value.included_in_pension_salary_basis != expected.GetProperty("included_in_pension_salary_basis").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxVacationCompensation.included_in_pension_salary_basis");
        Check(value.pension_premium_override, expected.GetProperty("pension_premium_override"));
    }
    internal static void Check(NativeTax.SwedishTaxRegularPensionPremium value, JsonElement expected)
    {
        if (value.is_some != expected.GetProperty("is_some").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxRegularPensionPremium.is_some");
        Check(value.monthly_override, expected.GetProperty("monthly_override"));
    }
    internal static void Check(NativeTax.SwedishTaxSalaryExchange value, JsonElement expected)
    {
        if (value.is_some != expected.GetProperty("is_some").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxSalaryExchange.is_some");
        if (value.sacrificed_salary != expected.GetProperty("sacrificed_salary").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxSalaryExchange.sacrificed_salary");
        if (value.employer_adds_uplift != expected.GetProperty("employer_adds_uplift").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxSalaryExchange.employer_adds_uplift");
        if (value.uplift_basis_points != expected.GetProperty("uplift_basis_points").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxSalaryExchange.uplift_basis_points");
        Check(value.previous_year_pension_salary_basis, expected.GetProperty("previous_year_pension_salary_basis"));
        Check(value.pension_and_insurance_costs_before_exchange, expected.GetProperty("pension_and_insurance_costs_before_exchange"));
    }
    internal static void Check(NativeTax.SwedishTaxIncomeEntry value, JsonElement expected)
    {
        if (value.id != expected.GetProperty("id").GetUInt64()) throw new InvalidOperationException("Value mismatch: SwedishTaxIncomeEntry.id");
        if (value.kind != expected.GetProperty("kind").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxIncomeEntry.kind");
        if (value.amount != expected.GetProperty("amount").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxIncomeEntry.amount");
        Check(value.start, expected.GetProperty("start"));
        Check(value.end, expected.GetProperty("end"));
        if (value.use_annual_daily_rate_for_partial_months != expected.GetProperty("use_annual_daily_rate_for_partial_months").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxIncomeEntry.use_annual_daily_rate_for_partial_months");
        if (value.payer_role != expected.GetProperty("payer_role").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxIncomeEntry.payer_role");
        if (value.own_company_sourced != expected.GetProperty("own_company_sourced").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxIncomeEntry.own_company_sourced");
        if (value.adjustment_applies != expected.GetProperty("adjustment_applies").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxIncomeEntry.adjustment_applies");
        if (value.use_full_year_projection_as_adjustment_basis != expected.GetProperty("use_full_year_projection_as_adjustment_basis").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxIncomeEntry.use_full_year_projection_as_adjustment_basis");
        Check(value.additional_withholding_per_payment, expected.GetProperty("additional_withholding_per_payment"));
        Check(value.actual_withholding, expected.GetProperty("actual_withholding"));
        Check(value.vacation_compensation, expected.GetProperty("vacation_compensation"));
        Check(value.regular_pension_premium, expected.GetProperty("regular_pension_premium"));
        Check(value.salary_exchange, expected.GetProperty("salary_exchange"));
        if (value.included_in_pension_salary_basis != expected.GetProperty("included_in_pension_salary_basis").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxIncomeEntry.included_in_pension_salary_basis");
    }
    internal static void Check(NativeTax.SwedishTaxDividendAllowanceInputs value, JsonElement expected)
    {
        if (value.one_person_company != expected.GetProperty("one_person_company").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceInputs.one_person_company");
        if (value.ownership_basis_points != expected.GetProperty("ownership_basis_points").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceInputs.ownership_basis_points");
        if (value.other_qualified_ownership_basis_points != expected.GetProperty("other_qualified_ownership_basis_points").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceInputs.other_qualified_ownership_basis_points");
        if (value.spouse_ownership_basis_points != expected.GetProperty("spouse_ownership_basis_points").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceInputs.spouse_ownership_basis_points");
        if (value.company_cash_payroll_2026 != expected.GetProperty("company_cash_payroll_2026").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceInputs.company_cash_payroll_2026");
        if (value.highest_related_cash_salary_2026 != expected.GetProperty("highest_related_cash_salary_2026").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceInputs.highest_related_cash_salary_2026");
        if (value.acquisition_cost != expected.GetProperty("acquisition_cost").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceInputs.acquisition_cost");
        Check(value.acquisition_cost_interest_basis_points, expected.GetProperty("acquisition_cost_interest_basis_points"));
        if (value.saved_allowance != expected.GetProperty("saved_allowance").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceInputs.saved_allowance");
    }
    internal static void Check(NativeTax.SwedishTaxPlanRequest value, JsonElement expected)
    {
        if (value.table != expected.GetProperty("table").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanRequest.table");
        if (value.age_group != expected.GetProperty("age_group").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanRequest.age_group");
        if ((value.entries_count != 0 && value.entries == null)) throw new InvalidOperationException("Invalid Rust result buffer");
        var rows = expected.GetProperty("entries");
        if ((nuint)rows.GetArrayLength() != value.entries_count) throw new InvalidOperationException("Withholding count mismatch");
        for (int i = 0; i < rows.GetArrayLength(); i++) Check(value.entries[i], rows[i]);
        if (value.entries_count != expected.GetProperty("entries_count").GetUInt64()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanRequest.entries_count");
        Check(value.adjustment_percent, expected.GetProperty("adjustment_percent"));
        Check(value.dividend_allowance, expected.GetProperty("dividend_allowance"));
    }
    internal static void Check(NativeTax.SwedishTaxDividendAllowanceResult value, JsonElement expected)
    {
        if (value.status != expected.GetProperty("status").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceResult.status");
        if (value.issue_kind != expected.GetProperty("issue_kind").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceResult.issue_kind");
        if (value.basic_amount != expected.GetProperty("basic_amount").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceResult.basic_amount");
        if (value.owner_cash_salary != expected.GetProperty("owner_cash_salary").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceResult.owner_cash_salary");
        if (value.company_cash_payroll != expected.GetProperty("company_cash_payroll").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceResult.company_cash_payroll");
        if (value.joint_wage_basis != expected.GetProperty("joint_wage_basis").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceResult.joint_wage_basis");
        if (value.joint_wage_basis_after_deduction != expected.GetProperty("joint_wage_basis_after_deduction").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceResult.joint_wage_basis_after_deduction");
        if (value.wage_allowance_before_cap != expected.GetProperty("wage_allowance_before_cap").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceResult.wage_allowance_before_cap");
        if (value.wage_cap_salary != expected.GetProperty("wage_cap_salary").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceResult.wage_cap_salary");
        if (value.wage_cap != expected.GetProperty("wage_cap").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceResult.wage_cap");
        if (value.wage_allowance != expected.GetProperty("wage_allowance").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceResult.wage_allowance");
        if (value.acquisition_cost_interest_basis != expected.GetProperty("acquisition_cost_interest_basis").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceResult.acquisition_cost_interest_basis");
        if (value.acquisition_cost_interest != expected.GetProperty("acquisition_cost_interest").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceResult.acquisition_cost_interest");
        if (value.saved_allowance != expected.GetProperty("saved_allowance").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceResult.saved_allowance");
        if (value.total != expected.GetProperty("total").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceResult.total");
        if (value.tax_at_twenty_percent != expected.GetProperty("tax_at_twenty_percent").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceResult.tax_at_twenty_percent");
        if (value.net_after_twenty_percent_tax != expected.GetProperty("net_after_twenty_percent_tax").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxDividendAllowanceResult.net_after_twenty_percent_tax");
    }
    internal static void Check(NativeTax.SwedishTaxPlanTotals value, JsonElement expected)
    {
        if (value.work_income != expected.GetProperty("work_income").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanTotals.work_income");
        if (value.pension_income != expected.GetProperty("pension_income").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanTotals.pension_income");
        if (value.dividend_income != expected.GetProperty("dividend_income").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanTotals.dividend_income");
        if (value.sgi_annual_rate != expected.GetProperty("sgi_annual_rate").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanTotals.sgi_annual_rate");
        if (value.adjustment_basis_work_income != expected.GetProperty("adjustment_basis_work_income").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanTotals.adjustment_basis_work_income");
        if (value.pension_salary_basis != expected.GetProperty("pension_salary_basis").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanTotals.pension_salary_basis");
        if (value.regular_pension_premiums != expected.GetProperty("regular_pension_premiums").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanTotals.regular_pension_premiums");
        if (value.vacation_pension_premiums != expected.GetProperty("vacation_pension_premiums").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanTotals.vacation_pension_premiums");
        if (value.salary_exchange_sacrifice != expected.GetProperty("salary_exchange_sacrifice").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanTotals.salary_exchange_sacrifice");
        if (value.salary_exchange_pension_contributions != expected.GetProperty("salary_exchange_pension_contributions").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanTotals.salary_exchange_pension_contributions");
        if (value.ordinary_income != expected.GetProperty("ordinary_income").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanTotals.ordinary_income");
        if (value.monthly_taxable_income != expected.GetProperty("monthly_taxable_income").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanTotals.monthly_taxable_income");
        if (value.gross_income != expected.GetProperty("gross_income").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanTotals.gross_income");
        if (value.total_employer_pension_contributions != expected.GetProperty("total_employer_pension_contributions").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanTotals.total_employer_pension_contributions");
        if (!double.IsFinite(value.employer_pension_share_of_basis) || Math.Abs(value.employer_pension_share_of_basis - expected.GetProperty("employer_pension_share_of_basis").GetDouble()) > 1e-10) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanTotals.employer_pension_share_of_basis");
    }
    internal static void Check(NativeTax.SwedishTaxMonthlyAmounts value, JsonElement expected)
    {
        if (value.january != expected.GetProperty("january").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxMonthlyAmounts.january");
        if (value.february != expected.GetProperty("february").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxMonthlyAmounts.february");
        if (value.march != expected.GetProperty("march").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxMonthlyAmounts.march");
        if (value.april != expected.GetProperty("april").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxMonthlyAmounts.april");
        if (value.may != expected.GetProperty("may").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxMonthlyAmounts.may");
        if (value.june != expected.GetProperty("june").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxMonthlyAmounts.june");
        if (value.july != expected.GetProperty("july").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxMonthlyAmounts.july");
        if (value.august != expected.GetProperty("august").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxMonthlyAmounts.august");
        if (value.september != expected.GetProperty("september").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxMonthlyAmounts.september");
        if (value.october != expected.GetProperty("october").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxMonthlyAmounts.october");
        if (value.november != expected.GetProperty("november").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxMonthlyAmounts.november");
        if (value.december != expected.GetProperty("december").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxMonthlyAmounts.december");
    }
    internal static void Check(NativeTax.SwedishTaxExchangeAllowance value, JsonElement expected)
    {
        if (value.ceiling != expected.GetProperty("ceiling").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxExchangeAllowance.ceiling");
        if (value.pension_salary_basis_before != expected.GetProperty("pension_salary_basis_before").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxExchangeAllowance.pension_salary_basis_before");
        if (value.pension_salary_basis_after != expected.GetProperty("pension_salary_basis_after").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxExchangeAllowance.pension_salary_basis_after");
        Check(value.previous_year_pension_salary_basis, expected.GetProperty("previous_year_pension_salary_basis"));
        Check(value.pension_and_insurance_costs_before_exchange, expected.GetProperty("pension_and_insurance_costs_before_exchange"));
        if (value.pension_contributions_before != expected.GetProperty("pension_contributions_before").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxExchangeAllowance.pension_contributions_before");
        if (value.regular_pension_premiums != expected.GetProperty("regular_pension_premiums").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxExchangeAllowance.regular_pension_premiums");
        if (value.vacation_pension_premiums != expected.GetProperty("vacation_pension_premiums").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxExchangeAllowance.vacation_pension_premiums");
        if (value.other_exchange_contributions != expected.GetProperty("other_exchange_contributions").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxExchangeAllowance.other_exchange_contributions");
        if (value.selected_exchange_contribution != expected.GetProperty("selected_exchange_contribution").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxExchangeAllowance.selected_exchange_contribution");
        if (value.total_employer_pension_contributions != expected.GetProperty("total_employer_pension_contributions").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxExchangeAllowance.total_employer_pension_contributions");
        if (value.available_contribution != expected.GetProperty("available_contribution").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxExchangeAllowance.available_contribution");
        if (value.maximum_sacrifice != expected.GetProperty("maximum_sacrifice").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxExchangeAllowance.maximum_sacrifice");
        if (!double.IsFinite(value.contribution_share_of_basis) || Math.Abs(value.contribution_share_of_basis - expected.GetProperty("contribution_share_of_basis").GetDouble()) > 1e-10) throw new InvalidOperationException("Value mismatch: SwedishTaxExchangeAllowance.contribution_share_of_basis");
    }
    internal static void Check(NativeTax.SwedishTaxEntrySupport value, JsonElement expected)
    {
        if (value.status != expected.GetProperty("status").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxEntrySupport.status");
        if (value.entry_id != expected.GetProperty("entry_id").GetUInt64()) throw new InvalidOperationException("Value mismatch: SwedishTaxEntrySupport.entry_id");
        if (value.annual_amount != expected.GetProperty("annual_amount").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxEntrySupport.annual_amount");
        if (value.total_annual_amount != expected.GetProperty("total_annual_amount").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxEntrySupport.total_annual_amount");
        if (value.withholding_payment_count != expected.GetProperty("withholding_payment_count").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxEntrySupport.withholding_payment_count");
        if (value.requested_additional_withholding != expected.GetProperty("requested_additional_withholding").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxEntrySupport.requested_additional_withholding");
        if (value.vacation_compensation_amount != expected.GetProperty("vacation_compensation_amount").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxEntrySupport.vacation_compensation_amount");
        if (value.regular_pension_premium_amount != expected.GetProperty("regular_pension_premium_amount").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxEntrySupport.regular_pension_premium_amount");
        if (value.vacation_pension_premium_amount != expected.GetProperty("vacation_pension_premium_amount").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxEntrySupport.vacation_pension_premium_amount");
        if (value.salary_exchange_sacrifice != expected.GetProperty("salary_exchange_sacrifice").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxEntrySupport.salary_exchange_sacrifice");
        if (value.salary_exchange_pension_contribution != expected.GetProperty("salary_exchange_pension_contribution").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxEntrySupport.salary_exchange_pension_contribution");
        if (value.pension_salary_basis_amount != expected.GetProperty("pension_salary_basis_amount").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxEntrySupport.pension_salary_basis_amount");
        if (value.full_year_adjustment_basis_amount != expected.GetProperty("full_year_adjustment_basis_amount").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxEntrySupport.full_year_adjustment_basis_amount");
        if (value.is_valid != expected.GetProperty("is_valid").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxEntrySupport.is_valid");
        if (value.pension_benchmark_monthly != expected.GetProperty("pension_benchmark_monthly").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxEntrySupport.pension_benchmark_monthly");
        if (value.suggested_vacation_days != expected.GetProperty("suggested_vacation_days").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxEntrySupport.suggested_vacation_days");
        if (!double.IsFinite(value.vacation_amount_per_day) || Math.Abs(value.vacation_amount_per_day - expected.GetProperty("vacation_amount_per_day").GetDouble()) > 1e-10) throw new InvalidOperationException("Value mismatch: SwedishTaxEntrySupport.vacation_amount_per_day");
        Check(value.monthly_amounts, expected.GetProperty("monthly_amounts"));
        if (value.has_allowance != expected.GetProperty("has_allowance").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxEntrySupport.has_allowance");
        Check(value.allowance, expected.GetProperty("allowance"));
    }
    internal static void Check(NativeTax.SwedishTaxPlanSupport value, JsonElement expected)
    {
        if (value.status != expected.GetProperty("status").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanSupport.status");
        if (value.issue_kind != expected.GetProperty("issue_kind").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanSupport.issue_kind");
        if (value.issue_entry_id != expected.GetProperty("issue_entry_id").GetUInt64()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanSupport.issue_entry_id");
        if (value.issue_maximum != expected.GetProperty("issue_maximum").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanSupport.issue_maximum");
        Check(value.totals, expected.GetProperty("totals"));
        if (value.has_uniform_monthly_table_reference != expected.GetProperty("has_uniform_monthly_table_reference").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanSupport.has_uniform_monthly_table_reference");
        if (value.salary_column != expected.GetProperty("salary_column").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanSupport.salary_column");
        if (value.pension_column != expected.GetProperty("pension_column").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanSupport.pension_column");
        if (value.entries_count > value.entries_capacity || (value.entries_count != 0 && value.entries == null)) throw new InvalidOperationException("Invalid Rust result buffer");
        var rows = expected.GetProperty("entries");
        if ((nuint)rows.GetArrayLength() != value.entries_count) throw new InvalidOperationException("Withholding count mismatch");
        for (int i = 0; i < rows.GetArrayLength(); i++) Check(value.entries[i], rows[i]);
        if (value.entries_count != expected.GetProperty("entries_count").GetUInt64()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanSupport.entries_count");
    }
    internal static void Check(NativeTax.SwedishTaxPlanningPolicy value, JsonElement expected)
    {
        if (value.regular_pension_monthly_threshold != expected.GetProperty("regular_pension_monthly_threshold").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanningPolicy.regular_pension_monthly_threshold");
        if (value.default_vacation_rate_basis_points != expected.GetProperty("default_vacation_rate_basis_points").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanningPolicy.default_vacation_rate_basis_points");
        if (value.default_exchange_uplift_basis_points != expected.GetProperty("default_exchange_uplift_basis_points").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanningPolicy.default_exchange_uplift_basis_points");
        if (value.employer_pension_allowance_maximum != expected.GetProperty("employer_pension_allowance_maximum").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanningPolicy.employer_pension_allowance_maximum");
        if (value.acquisition_cost_threshold != expected.GetProperty("acquisition_cost_threshold").GetUInt32()) throw new InvalidOperationException("Value mismatch: SwedishTaxPlanningPolicy.acquisition_cost_threshold");
    }
}
