// Generated by generate-bindings.py. Native reference fixtures.
#include <inttypes.h>
#include <stdio.h>
static inline void print_SwedishTaxDeductionResult(SwedishTaxDeductionResult value) {
    putchar('{');
    printf("\"status\":");
    printf("%" PRIu32, value.status);
    printf(",\"kind\":");
    printf("%" PRIu32, value.kind);
    printf(",\"value\":");
    printf("%" PRIu32, value.value);
    putchar('}');
}
static inline void print_SwedishTaxAnnualTaxResult(SwedishTaxAnnualTaxResult value) {
    putchar('{');
    printf("\"status\":");
    printf("%" PRIu32, value.status);
    printf(",\"assessed_income\":");
    printf("%" PRIu32, value.assessed_income);
    printf(",\"basic_allowance\":");
    printf("%" PRIu32, value.basic_allowance);
    printf(",\"taxable_income\":");
    printf("%" PRIu32, value.taxable_income);
    printf(",\"state_income_tax\":");
    printf("%" PRIu32, value.state_income_tax);
    printf(",\"municipal_income_tax\":");
    printf("%" PRIu32, value.municipal_income_tax);
    printf(",\"burial_and_religious_fee\":");
    printf("%" PRIu32, value.burial_and_religious_fee);
    printf(",\"pension_fee\":");
    printf("%" PRIu32, value.pension_fee);
    printf(",\"pension_fee_credit\":");
    printf("%" PRIu32, value.pension_fee_credit);
    printf(",\"work_income_credit\":");
    printf("%" PRIu32, value.work_income_credit);
    printf(",\"sickness_compensation_credit\":");
    printf("%" PRIu32, value.sickness_compensation_credit);
    printf(",\"earned_income_credit\":");
    printf("%" PRIu32, value.earned_income_credit);
    printf(",\"public_service_fee\":");
    printf("%" PRIu32, value.public_service_fee);
    printf(",\"total\":");
    printf("%" PRIu32, value.total);
    putchar('}');
}
static inline void print_SwedishTaxAdjustmentCalibration(SwedishTaxAdjustmentCalibration value) {
    putchar('{');
    printf("\"basis_income\":");
    printf("%" PRIu32, value.basis_income);
    printf(",\"percent\":");
    printf("%" PRIu32, value.percent);
    printf(",\"formula_tax_at_basis\":");
    printf("%" PRIu32, value.formula_tax_at_basis);
    printf(",\"assumed_tax_at_basis\":");
    printf("%" PRIu32, value.assumed_tax_at_basis);
    printf(",\"implied_tax_adjustment\":");
    printf("%" PRId64, value.implied_tax_adjustment);
    printf(",\"projected_ordinary_tax\":");
    printf("%" PRIu32, value.projected_ordinary_tax);
    putchar('}');
}
static inline void print_SwedishTaxWithholdingEntry(SwedishTaxWithholdingEntry value) {
    putchar('{');
    printf("\"entry_id\":");
    printf("%" PRIu64, value.entry_id);
    printf(",\"gross\":");
    printf("%" PRIu32, value.gross);
    printf(",\"withheld\":");
    printf("%" PRIu32, value.withheld);
    printf(",\"regular_withheld\":");
    printf("%" PRIu32, value.regular_withheld);
    printf(",\"supplemental_withheld\":");
    printf("%" PRIu32, value.supplemental_withheld);
    printf(",\"additional_withheld\":");
    printf("%" PRIu32, value.additional_withheld);
    printf(",\"rule_kind\":");
    printf("%" PRIu32, value.rule_kind);
    printf(",\"rule_column\":");
    printf("%" PRIu32, value.rule_column);
    printf(",\"rule_percent\":");
    printf("%" PRIu32, value.rule_percent);
    putchar('}');
}
static inline void print_SwedishTaxIncomeBasis(SwedishTaxIncomeBasis value) {
    putchar('{');
    printf("\"kind\":");
    printf("%" PRIu32, value.kind);
    printf(",\"estimated_basis\":");
    printf("%" PRIu32, value.estimated_basis);
    printf(",\"maximum_basis\":");
    printf("%" PRIu32, value.maximum_basis);
    putchar('}');
}
static inline void print_SwedishTaxCalculationResult(SwedishTaxCalculationResult value) {
    putchar('{');
    printf("\"status\":");
    printf("%" PRIu32, value.status);
    printf(",\"monthly_income\":");
    printf("%" PRIu32, value.monthly_income);
    printf(",\"annual_income\":");
    printf("%" PRIu32, value.annual_income);
    printf(",\"ordinary_income\":");
    printf("%" PRIu32, value.ordinary_income);
    printf(",\"work_income\":");
    printf("%" PRIu32, value.work_income);
    printf(",\"pension_income\":");
    printf("%" PRIu32, value.pension_income);
    printf(",\"dividend_income\":");
    printf("%" PRIu32, value.dividend_income);
    printf(",\"sgi_annual_rate\":");
    printf("%" PRIu32, value.sgi_annual_rate);
    printf(",\"deduction_kind\":");
    printf("%" PRIu32, value.deduction_kind);
    printf(",\"deduction_value\":");
    printf("%" PRIu32, value.deduction_value);
    printf(",\"annual_tax\":");
    print_SwedishTaxAnnualTaxResult(value.annual_tax);
    printf(",\"has_adjustment_calibration\":");
    printf("%" PRIu32, value.has_adjustment_calibration);
    printf(",\"adjustment_calibration\":");
    print_SwedishTaxAdjustmentCalibration(value.adjustment_calibration);
    printf(",\"ordinary_final_tax\":");
    printf("%" PRIu32, value.ordinary_final_tax);
    printf(",\"dividend_tax\":");
    printf("%" PRIu32, value.dividend_tax);
    printf(",\"total_tax\":");
    printf("%" PRIu32, value.total_tax);
    printf(",\"withholding_total\":");
    printf("%" PRIu32, value.withholding_total);
    printf(",\"withholding_entries\":");
    putchar('[');
    for (size_t i = 0; i < value.withholding_entries_count; i++) {
        if (i) putchar(',');
        print_SwedishTaxWithholdingEntry(value.withholding_entries[i]);
    }
    putchar(']');
    printf(",\"withholding_entries_count\":");
    printf("%zu", value.withholding_entries_count);
    printf(",\"withheld_tax\":");
    printf("%" PRIu32, value.withheld_tax);
    printf(",\"regular_pension_premiums\":");
    printf("%" PRIu32, value.regular_pension_premiums);
    printf(",\"vacation_pension_premiums\":");
    printf("%" PRIu32, value.vacation_pension_premiums);
    printf(",\"salary_exchange_sacrifice\":");
    printf("%" PRIu32, value.salary_exchange_sacrifice);
    printf(",\"salary_exchange_pension_contributions\":");
    printf("%" PRIu32, value.salary_exchange_pension_contributions);
    printf(",\"pension_salary_basis\":");
    printf("%" PRIu32, value.pension_salary_basis);
    printf(",\"employer_pension_contributions\":");
    printf("%" PRIu32, value.employer_pension_contributions);
    printf(",\"marginal_rate\":");
    printf("%.17g", value.marginal_rate);
    printf(",\"pension_progress\":");
    print_SwedishTaxIncomeBasis(value.pension_progress);
    printf(",\"sgi_progress\":");
    print_SwedishTaxIncomeBasis(value.sgi_progress);
    putchar('}');
}
static inline void print_SwedishTaxDate(SwedishTaxDate value) {
    putchar('{');
    printf("\"month\":");
    printf("%" PRIu32, value.month);
    printf(",\"day\":");
    printf("%" PRIu32, value.day);
    putchar('}');
}
static inline void print_SwedishTaxOptionalU32(SwedishTaxOptionalU32 value) {
    putchar('{');
    printf("\"is_some\":");
    printf("%" PRIu32, value.is_some);
    printf(",\"value\":");
    printf("%" PRIu32, value.value);
    putchar('}');
}
static inline void print_SwedishTaxVacationCompensation(SwedishTaxVacationCompensation value) {
    putchar('{');
    printf("\"is_some\":");
    printf("%" PRIu32, value.is_some);
    printf(",\"annual_entitlement_days\":");
    printf("%" PRIu32, value.annual_entitlement_days);
    printf(",\"payout_days\":");
    printf("%" PRIu32, value.payout_days);
    printf(",\"rate_basis_points\":");
    printf("%" PRIu32, value.rate_basis_points);
    printf(",\"included_in_pension_salary_basis\":");
    printf("%" PRIu32, value.included_in_pension_salary_basis);
    printf(",\"pension_premium_override\":");
    print_SwedishTaxOptionalU32(value.pension_premium_override);
    putchar('}');
}
static inline void print_SwedishTaxRegularPensionPremium(SwedishTaxRegularPensionPremium value) {
    putchar('{');
    printf("\"is_some\":");
    printf("%" PRIu32, value.is_some);
    printf(",\"monthly_override\":");
    print_SwedishTaxOptionalU32(value.monthly_override);
    putchar('}');
}
static inline void print_SwedishTaxSalaryExchange(SwedishTaxSalaryExchange value) {
    putchar('{');
    printf("\"is_some\":");
    printf("%" PRIu32, value.is_some);
    printf(",\"sacrificed_salary\":");
    printf("%" PRIu32, value.sacrificed_salary);
    printf(",\"employer_adds_uplift\":");
    printf("%" PRIu32, value.employer_adds_uplift);
    printf(",\"uplift_basis_points\":");
    printf("%" PRIu32, value.uplift_basis_points);
    printf(",\"previous_year_pension_salary_basis\":");
    print_SwedishTaxOptionalU32(value.previous_year_pension_salary_basis);
    printf(",\"pension_and_insurance_costs_before_exchange\":");
    print_SwedishTaxOptionalU32(value.pension_and_insurance_costs_before_exchange);
    putchar('}');
}
static inline void print_SwedishTaxIncomeEntry(SwedishTaxIncomeEntry value) {
    putchar('{');
    printf("\"id\":");
    printf("%" PRIu64, value.id);
    printf(",\"kind\":");
    printf("%" PRIu32, value.kind);
    printf(",\"amount\":");
    printf("%" PRIu32, value.amount);
    printf(",\"start\":");
    print_SwedishTaxDate(value.start);
    printf(",\"end\":");
    print_SwedishTaxDate(value.end);
    printf(",\"use_annual_daily_rate_for_partial_months\":");
    printf("%" PRIu32, value.use_annual_daily_rate_for_partial_months);
    printf(",\"payer_role\":");
    printf("%" PRIu32, value.payer_role);
    printf(",\"own_company_sourced\":");
    printf("%" PRIu32, value.own_company_sourced);
    printf(",\"adjustment_applies\":");
    printf("%" PRIu32, value.adjustment_applies);
    printf(",\"use_full_year_projection_as_adjustment_basis\":");
    printf("%" PRIu32, value.use_full_year_projection_as_adjustment_basis);
    printf(",\"additional_withholding_per_payment\":");
    print_SwedishTaxOptionalU32(value.additional_withholding_per_payment);
    printf(",\"actual_withholding\":");
    print_SwedishTaxOptionalU32(value.actual_withholding);
    printf(",\"vacation_compensation\":");
    print_SwedishTaxVacationCompensation(value.vacation_compensation);
    printf(",\"regular_pension_premium\":");
    print_SwedishTaxRegularPensionPremium(value.regular_pension_premium);
    printf(",\"salary_exchange\":");
    print_SwedishTaxSalaryExchange(value.salary_exchange);
    printf(",\"included_in_pension_salary_basis\":");
    printf("%" PRIu32, value.included_in_pension_salary_basis);
    putchar('}');
}
static inline void print_SwedishTaxDividendAllowanceInputs(SwedishTaxDividendAllowanceInputs value) {
    putchar('{');
    printf("\"one_person_company\":");
    printf("%" PRIu32, value.one_person_company);
    printf(",\"ownership_basis_points\":");
    printf("%" PRIu32, value.ownership_basis_points);
    printf(",\"other_qualified_ownership_basis_points\":");
    printf("%" PRIu32, value.other_qualified_ownership_basis_points);
    printf(",\"spouse_ownership_basis_points\":");
    printf("%" PRIu32, value.spouse_ownership_basis_points);
    printf(",\"company_cash_payroll_2026\":");
    printf("%" PRIu32, value.company_cash_payroll_2026);
    printf(",\"highest_related_cash_salary_2026\":");
    printf("%" PRIu32, value.highest_related_cash_salary_2026);
    printf(",\"acquisition_cost\":");
    printf("%" PRIu32, value.acquisition_cost);
    printf(",\"acquisition_cost_interest_basis_points\":");
    print_SwedishTaxOptionalU32(value.acquisition_cost_interest_basis_points);
    printf(",\"saved_allowance\":");
    printf("%" PRIu32, value.saved_allowance);
    putchar('}');
}
static inline void print_SwedishTaxPlanRequest(SwedishTaxPlanRequest value) {
    putchar('{');
    printf("\"table\":");
    printf("%" PRIu32, value.table);
    printf(",\"age_group\":");
    printf("%" PRIu32, value.age_group);
    printf(",\"entries\":");
    putchar('[');
    for (size_t i = 0; i < value.entries_count; i++) {
        if (i) putchar(',');
        print_SwedishTaxIncomeEntry(value.entries[i]);
    }
    putchar(']');
    printf(",\"entries_count\":");
    printf("%zu", value.entries_count);
    printf(",\"adjustment_percent\":");
    print_SwedishTaxOptionalU32(value.adjustment_percent);
    printf(",\"dividend_allowance\":");
    print_SwedishTaxDividendAllowanceInputs(value.dividend_allowance);
    putchar('}');
}
static inline void print_SwedishTaxDividendAllowanceResult(SwedishTaxDividendAllowanceResult value) {
    putchar('{');
    printf("\"status\":");
    printf("%" PRIu32, value.status);
    printf(",\"issue_kind\":");
    printf("%" PRIu32, value.issue_kind);
    printf(",\"basic_amount\":");
    printf("%" PRIu32, value.basic_amount);
    printf(",\"owner_cash_salary\":");
    printf("%" PRIu32, value.owner_cash_salary);
    printf(",\"company_cash_payroll\":");
    printf("%" PRIu32, value.company_cash_payroll);
    printf(",\"joint_wage_basis\":");
    printf("%" PRIu32, value.joint_wage_basis);
    printf(",\"joint_wage_basis_after_deduction\":");
    printf("%" PRIu32, value.joint_wage_basis_after_deduction);
    printf(",\"wage_allowance_before_cap\":");
    printf("%" PRIu32, value.wage_allowance_before_cap);
    printf(",\"wage_cap_salary\":");
    printf("%" PRIu32, value.wage_cap_salary);
    printf(",\"wage_cap\":");
    printf("%" PRIu32, value.wage_cap);
    printf(",\"wage_allowance\":");
    printf("%" PRIu32, value.wage_allowance);
    printf(",\"acquisition_cost_interest_basis\":");
    printf("%" PRIu32, value.acquisition_cost_interest_basis);
    printf(",\"acquisition_cost_interest\":");
    printf("%" PRIu32, value.acquisition_cost_interest);
    printf(",\"saved_allowance\":");
    printf("%" PRIu32, value.saved_allowance);
    printf(",\"total\":");
    printf("%" PRIu32, value.total);
    printf(",\"tax_at_twenty_percent\":");
    printf("%" PRIu32, value.tax_at_twenty_percent);
    printf(",\"net_after_twenty_percent_tax\":");
    printf("%" PRIu32, value.net_after_twenty_percent_tax);
    putchar('}');
}
static inline void print_SwedishTaxPlanTotals(SwedishTaxPlanTotals value) {
    putchar('{');
    printf("\"work_income\":");
    printf("%" PRIu32, value.work_income);
    printf(",\"pension_income\":");
    printf("%" PRIu32, value.pension_income);
    printf(",\"dividend_income\":");
    printf("%" PRIu32, value.dividend_income);
    printf(",\"sgi_annual_rate\":");
    printf("%" PRIu32, value.sgi_annual_rate);
    printf(",\"adjustment_basis_work_income\":");
    printf("%" PRIu32, value.adjustment_basis_work_income);
    printf(",\"pension_salary_basis\":");
    printf("%" PRIu32, value.pension_salary_basis);
    printf(",\"regular_pension_premiums\":");
    printf("%" PRIu32, value.regular_pension_premiums);
    printf(",\"vacation_pension_premiums\":");
    printf("%" PRIu32, value.vacation_pension_premiums);
    printf(",\"salary_exchange_sacrifice\":");
    printf("%" PRIu32, value.salary_exchange_sacrifice);
    printf(",\"salary_exchange_pension_contributions\":");
    printf("%" PRIu32, value.salary_exchange_pension_contributions);
    printf(",\"ordinary_income\":");
    printf("%" PRIu32, value.ordinary_income);
    printf(",\"monthly_taxable_income\":");
    printf("%" PRIu32, value.monthly_taxable_income);
    printf(",\"gross_income\":");
    printf("%" PRIu32, value.gross_income);
    printf(",\"total_employer_pension_contributions\":");
    printf("%" PRIu32, value.total_employer_pension_contributions);
    printf(",\"employer_pension_share_of_basis\":");
    printf("%.17g", value.employer_pension_share_of_basis);
    putchar('}');
}
static inline void print_SwedishTaxMonthlyAmounts(SwedishTaxMonthlyAmounts value) {
    putchar('{');
    printf("\"january\":");
    printf("%" PRIu32, value.january);
    printf(",\"february\":");
    printf("%" PRIu32, value.february);
    printf(",\"march\":");
    printf("%" PRIu32, value.march);
    printf(",\"april\":");
    printf("%" PRIu32, value.april);
    printf(",\"may\":");
    printf("%" PRIu32, value.may);
    printf(",\"june\":");
    printf("%" PRIu32, value.june);
    printf(",\"july\":");
    printf("%" PRIu32, value.july);
    printf(",\"august\":");
    printf("%" PRIu32, value.august);
    printf(",\"september\":");
    printf("%" PRIu32, value.september);
    printf(",\"october\":");
    printf("%" PRIu32, value.october);
    printf(",\"november\":");
    printf("%" PRIu32, value.november);
    printf(",\"december\":");
    printf("%" PRIu32, value.december);
    putchar('}');
}
static inline void print_SwedishTaxExchangeAllowance(SwedishTaxExchangeAllowance value) {
    putchar('{');
    printf("\"ceiling\":");
    printf("%" PRIu32, value.ceiling);
    printf(",\"pension_salary_basis_before\":");
    printf("%" PRIu32, value.pension_salary_basis_before);
    printf(",\"pension_salary_basis_after\":");
    printf("%" PRIu32, value.pension_salary_basis_after);
    printf(",\"previous_year_pension_salary_basis\":");
    print_SwedishTaxOptionalU32(value.previous_year_pension_salary_basis);
    printf(",\"pension_and_insurance_costs_before_exchange\":");
    print_SwedishTaxOptionalU32(value.pension_and_insurance_costs_before_exchange);
    printf(",\"pension_contributions_before\":");
    printf("%" PRIu32, value.pension_contributions_before);
    printf(",\"regular_pension_premiums\":");
    printf("%" PRIu32, value.regular_pension_premiums);
    printf(",\"vacation_pension_premiums\":");
    printf("%" PRIu32, value.vacation_pension_premiums);
    printf(",\"other_exchange_contributions\":");
    printf("%" PRIu32, value.other_exchange_contributions);
    printf(",\"selected_exchange_contribution\":");
    printf("%" PRIu32, value.selected_exchange_contribution);
    printf(",\"total_employer_pension_contributions\":");
    printf("%" PRIu32, value.total_employer_pension_contributions);
    printf(",\"available_contribution\":");
    printf("%" PRIu32, value.available_contribution);
    printf(",\"maximum_sacrifice\":");
    printf("%" PRIu32, value.maximum_sacrifice);
    printf(",\"contribution_share_of_basis\":");
    printf("%.17g", value.contribution_share_of_basis);
    putchar('}');
}
static inline void print_SwedishTaxEntrySupport(SwedishTaxEntrySupport value) {
    putchar('{');
    printf("\"status\":");
    printf("%" PRIu32, value.status);
    printf(",\"entry_id\":");
    printf("%" PRIu64, value.entry_id);
    printf(",\"annual_amount\":");
    printf("%" PRIu32, value.annual_amount);
    printf(",\"total_annual_amount\":");
    printf("%" PRIu32, value.total_annual_amount);
    printf(",\"withholding_payment_count\":");
    printf("%" PRIu32, value.withholding_payment_count);
    printf(",\"requested_additional_withholding\":");
    printf("%" PRIu32, value.requested_additional_withholding);
    printf(",\"vacation_compensation_amount\":");
    printf("%" PRIu32, value.vacation_compensation_amount);
    printf(",\"regular_pension_premium_amount\":");
    printf("%" PRIu32, value.regular_pension_premium_amount);
    printf(",\"vacation_pension_premium_amount\":");
    printf("%" PRIu32, value.vacation_pension_premium_amount);
    printf(",\"salary_exchange_sacrifice\":");
    printf("%" PRIu32, value.salary_exchange_sacrifice);
    printf(",\"salary_exchange_pension_contribution\":");
    printf("%" PRIu32, value.salary_exchange_pension_contribution);
    printf(",\"pension_salary_basis_amount\":");
    printf("%" PRIu32, value.pension_salary_basis_amount);
    printf(",\"full_year_adjustment_basis_amount\":");
    printf("%" PRIu32, value.full_year_adjustment_basis_amount);
    printf(",\"is_valid\":");
    printf("%" PRIu32, value.is_valid);
    printf(",\"pension_benchmark_monthly\":");
    printf("%" PRIu32, value.pension_benchmark_monthly);
    printf(",\"suggested_vacation_days\":");
    printf("%" PRIu32, value.suggested_vacation_days);
    printf(",\"vacation_amount_per_day\":");
    printf("%.17g", value.vacation_amount_per_day);
    printf(",\"monthly_amounts\":");
    print_SwedishTaxMonthlyAmounts(value.monthly_amounts);
    printf(",\"has_allowance\":");
    printf("%" PRIu32, value.has_allowance);
    printf(",\"allowance\":");
    print_SwedishTaxExchangeAllowance(value.allowance);
    putchar('}');
}
static inline void print_SwedishTaxPlanSupport(SwedishTaxPlanSupport value) {
    putchar('{');
    printf("\"status\":");
    printf("%" PRIu32, value.status);
    printf(",\"issue_kind\":");
    printf("%" PRIu32, value.issue_kind);
    printf(",\"issue_entry_id\":");
    printf("%" PRIu64, value.issue_entry_id);
    printf(",\"issue_maximum\":");
    printf("%" PRIu32, value.issue_maximum);
    printf(",\"totals\":");
    print_SwedishTaxPlanTotals(value.totals);
    printf(",\"has_uniform_monthly_table_reference\":");
    printf("%" PRIu32, value.has_uniform_monthly_table_reference);
    printf(",\"salary_column\":");
    printf("%" PRIu32, value.salary_column);
    printf(",\"pension_column\":");
    printf("%" PRIu32, value.pension_column);
    printf(",\"entries\":");
    putchar('[');
    for (size_t i = 0; i < value.entries_count; i++) {
        if (i) putchar(',');
        print_SwedishTaxEntrySupport(value.entries[i]);
    }
    putchar(']');
    printf(",\"entries_count\":");
    printf("%zu", value.entries_count);
    putchar('}');
}
static inline void print_SwedishTaxPlanningPolicy(SwedishTaxPlanningPolicy value) {
    putchar('{');
    printf("\"regular_pension_monthly_threshold\":");
    printf("%" PRIu32, value.regular_pension_monthly_threshold);
    printf(",\"default_vacation_rate_basis_points\":");
    printf("%" PRIu32, value.default_vacation_rate_basis_points);
    printf(",\"default_exchange_uplift_basis_points\":");
    printf("%" PRIu32, value.default_exchange_uplift_basis_points);
    printf(",\"employer_pension_allowance_maximum\":");
    printf("%" PRIu32, value.employer_pension_allowance_maximum);
    printf(",\"acquisition_cost_threshold\":");
    printf("%" PRIu32, value.acquisition_cost_threshold);
    putchar('}');
}
